#!/usr/bin/env bash

BACKUP=~/.tmp/bkp
mkdir -p $BACKUP

function backup() {
  local source=$1

  if [ -f $source ]; then
    echo "Moving $source to $BACKUP"
    mv $source $BACKUP
  fi
}

backup  ~/.vim
backup ~/.ctags
backup ~/.william/bin/composer.phar
backup ~/.gitconfig
backup ~/.gitignore_global
backup ~/.gvimrc
backup ~/.ideavimrc
backup ~/.nvim
backup ~/.nvimrc
backup ~/.tmux
backup ~/.vim
backup ~/.vimrc
backup ~/.config/nvim
