source ~/.vim/plugins.vim

let g:mapleader=','
set backspace=indent,eol,start
set relativenumber
set number
set tabstop=4
set shiftwidth=4
set autoindent expandtab

if has("autocmd")
au BufReadPost * if line("`\"") > 1 && line("`\"") <= line("$") | exe "normal! g`\"" | endif
" for simplicity, \"  au BufReadPost * exe \"normal! g`\"", is Okay.
endif
